autofetch_sources: True

networks:
  default: mainnet-fork

dotenv: .env

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.5.0

compiler:
    solc:
        remappings:
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.2"
